# Generated by Django 5.1.5 on 2025-01-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image_path', models.ImageField(blank=True, default='no_image_available.png', null=True, upload_to='brand')),
            ],
            options={
                'db_table': 'brand',
            },
        ),
    ]
