# Generated by Django 5.1.5 on 2025-01-28 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_orderitem'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderitem',
            table='order_Item',
        ),
    ]
